from mrs.services.medicines import create_medicine

CATEGORIES = [
  "most_bought",
  "generic",
  "prescription_required",
  "otc",
  "ayurvedic",
  "personal_care",
  "vitamins_supplements",
  "baby_care",
  "first_aid",
  "chronic_care",
]

MEDICINES = [
  # ── Most Bought ──────────────────────────────────────────
  {
    "name": "Dolo 650",
    "description": "Paracetamol 650mg tablet for fever, headache, and body pain relief.",
    "category": "most_bought",
    "manufacturer": "Micro Labs Ltd",
    "price": 30.0,
    "discount_price": 25.0,
    "image_url": "https://placehold.co/200x200/0d9488/ffffff?text=Dolo+650",
    "dosage_form": "Tablet",
    "pack_size": "15 tablets",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Crocin Advance",
    "description": "Paracetamol 500mg tablet for quick relief from pain and fever.",
    "category": "most_bought",
    "manufacturer": "GSK Pharma",
    "price": 28.0,
    "discount_price": 24.0,
    "image_url": "https://placehold.co/200x200/0d9488/ffffff?text=Crocin",
    "dosage_form": "Tablet",
    "pack_size": "15 tablets",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Combiflam",
    "description": "Ibuprofen 400mg + Paracetamol 325mg for pain, inflammation, and fever.",
    "category": "most_bought",
    "manufacturer": "Sanofi India",
    "price": 38.0,
    "discount_price": 32.0,
    "image_url": "https://placehold.co/200x200/0d9488/ffffff?text=Combiflam",
    "dosage_form": "Tablet",
    "pack_size": "20 tablets",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Pan-D",
    "description": "Pantoprazole 40mg + Domperidone 30mg for acidity and gastric relief.",
    "category": "most_bought",
    "manufacturer": "Alkem Labs",
    "price": 115.0,
    "discount_price": 95.0,
    "image_url": "https://placehold.co/200x200/0d9488/ffffff?text=Pan-D",
    "dosage_form": "Capsule",
    "pack_size": "15 capsules",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Allegra 120mg",
    "description": "Fexofenadine 120mg for allergy relief — sneezing, runny nose, itching.",
    "category": "most_bought",
    "manufacturer": "Sanofi India",
    "price": 170.0,
    "discount_price": 148.0,
    "image_url": "https://placehold.co/200x200/0d9488/ffffff?text=Allegra",
    "dosage_form": "Tablet",
    "pack_size": "10 tablets",
    "requires_prescription": False,
    "in_stock": True,
  },

  # ── Generic Medicines ───────────────────────────────────
  {
    "name": "Paracetamol 500mg (Generic)",
    "description": "Generic paracetamol for pain and fever. Same efficacy, lower cost.",
    "category": "generic",
    "manufacturer": "Cipla Ltd",
    "price": 12.0,
    "discount_price": 10.0,
    "image_url": "https://placehold.co/200x200/6366f1/ffffff?text=Paracetamol",
    "dosage_form": "Tablet",
    "pack_size": "10 tablets",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Ibuprofen 400mg (Generic)",
    "description": "Generic ibuprofen for inflammation, pain, and mild fever.",
    "category": "generic",
    "manufacturer": "Cipla Ltd",
    "price": 18.0,
    "discount_price": 14.0,
    "image_url": "https://placehold.co/200x200/6366f1/ffffff?text=Ibuprofen",
    "dosage_form": "Tablet",
    "pack_size": "10 tablets",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Cetirizine 10mg (Generic)",
    "description": "Generic antihistamine for cold, allergy, and hay fever symptoms.",
    "category": "generic",
    "manufacturer": "Sun Pharma",
    "price": 15.0,
    "discount_price": 10.0,
    "image_url": "https://placehold.co/200x200/6366f1/ffffff?text=Cetirizine",
    "dosage_form": "Tablet",
    "pack_size": "10 tablets",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Metformin 500mg (Generic)",
    "description": "Generic metformin for type 2 diabetes blood sugar management.",
    "category": "generic",
    "manufacturer": "USV Pvt Ltd",
    "price": 22.0,
    "discount_price": 18.0,
    "image_url": "https://placehold.co/200x200/6366f1/ffffff?text=Metformin",
    "dosage_form": "Tablet",
    "pack_size": "20 tablets",
    "requires_prescription": True,
    "in_stock": True,
  },
  {
    "name": "Omeprazole 20mg (Generic)",
    "description": "Generic proton pump inhibitor for acidity and GERD.",
    "category": "generic",
    "manufacturer": "Dr. Reddy's",
    "price": 35.0,
    "discount_price": 28.0,
    "image_url": "https://placehold.co/200x200/6366f1/ffffff?text=Omeprazole",
    "dosage_form": "Capsule",
    "pack_size": "15 capsules",
    "requires_prescription": False,
    "in_stock": True,
  },

  # ── Prescription Required ───────────────────────────────
  {
    "name": "Augmentin 625 Duo",
    "description": "Amoxicillin + Clavulanic acid antibiotic for bacterial infections.",
    "category": "prescription_required",
    "manufacturer": "GSK Pharma",
    "price": 220.0,
    "discount_price": 195.0,
    "image_url": "https://placehold.co/200x200/dc2626/ffffff?text=Augmentin",
    "dosage_form": "Tablet",
    "pack_size": "10 tablets",
    "requires_prescription": True,
    "in_stock": True,
  },
  {
    "name": "Azithromycin 500mg",
    "description": "Broad-spectrum antibiotic for respiratory and skin infections.",
    "category": "prescription_required",
    "manufacturer": "Cipla Ltd",
    "price": 95.0,
    "discount_price": 80.0,
    "image_url": "https://placehold.co/200x200/dc2626/ffffff?text=Azithromycin",
    "dosage_form": "Tablet",
    "pack_size": "3 tablets",
    "requires_prescription": True,
    "in_stock": True,
  },
  {
    "name": "Ciprofloxacin 500mg",
    "description": "Fluoroquinolone antibiotic for urinary tract and GI infections.",
    "category": "prescription_required",
    "manufacturer": "Sun Pharma",
    "price": 65.0,
    "discount_price": 52.0,
    "image_url": "https://placehold.co/200x200/dc2626/ffffff?text=Cipro",
    "dosage_form": "Tablet",
    "pack_size": "10 tablets",
    "requires_prescription": True,
    "in_stock": True,
  },
  {
    "name": "Amoxicillin 500mg",
    "description": "Penicillin antibiotic for ear, nose, throat, and urinary infections.",
    "category": "prescription_required",
    "manufacturer": "Alkem Labs",
    "price": 85.0,
    "discount_price": 72.0,
    "image_url": "https://placehold.co/200x200/dc2626/ffffff?text=Amoxicillin",
    "dosage_form": "Capsule",
    "pack_size": "10 capsules",
    "requires_prescription": True,
    "in_stock": True,
  },
  {
    "name": "Prednisolone 10mg",
    "description": "Corticosteroid for severe allergies, asthma, and inflammatory conditions.",
    "category": "prescription_required",
    "manufacturer": "Wyeth",
    "price": 40.0,
    "discount_price": 34.0,
    "image_url": "https://placehold.co/200x200/dc2626/ffffff?text=Prednisolone",
    "dosage_form": "Tablet",
    "pack_size": "10 tablets",
    "requires_prescription": True,
    "in_stock": True,
  },

  # ── OTC (Over The Counter) ─────────────────────────────
  {
    "name": "Vicks VapoRub",
    "description": "Topical ointment for cold and cough relief. Apply on chest and throat.",
    "category": "otc",
    "manufacturer": "P&G Health",
    "price": 95.0,
    "discount_price": 85.0,
    "image_url": "https://placehold.co/200x200/f59e0b/ffffff?text=Vicks",
    "dosage_form": "Ointment",
    "pack_size": "50ml",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Strepsils",
    "description": "Medicated lozenges for sore throat, cough, and throat irritation.",
    "category": "otc",
    "manufacturer": "Reckitt",
    "price": 55.0,
    "discount_price": 48.0,
    "image_url": "https://placehold.co/200x200/f59e0b/ffffff?text=Strepsils",
    "dosage_form": "Lozenge",
    "pack_size": "8 lozenges",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Digene Gel",
    "description": "Antacid gel for instant relief from acidity, gas, and bloating.",
    "category": "otc",
    "manufacturer": "Abbott India",
    "price": 75.0,
    "discount_price": 65.0,
    "image_url": "https://placehold.co/200x200/f59e0b/ffffff?text=Digene",
    "dosage_form": "Gel",
    "pack_size": "200ml",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Benadryl Cough Syrup",
    "description": "Diphenhydramine cough syrup for dry and wet cough relief.",
    "category": "otc",
    "manufacturer": "Johnson & Johnson",
    "price": 105.0,
    "discount_price": 92.0,
    "image_url": "https://placehold.co/200x200/f59e0b/ffffff?text=Benadryl",
    "dosage_form": "Syrup",
    "pack_size": "100ml",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Electral Powder",
    "description": "ORS powder for rehydration during diarrhoea, vomiting, and dehydration.",
    "category": "otc",
    "manufacturer": "FDC Ltd",
    "price": 22.0,
    "discount_price": 18.0,
    "image_url": "https://placehold.co/200x200/f59e0b/ffffff?text=Electral",
    "dosage_form": "Powder",
    "pack_size": "4 sachets",
    "requires_prescription": False,
    "in_stock": True,
  },

  # ── Ayurvedic ──────────────────────────────────────────
  {
    "name": "Dabur Chyawanprash",
    "description": "Traditional Ayurvedic immunity booster with Amla and 40+ herbs.",
    "category": "ayurvedic",
    "manufacturer": "Dabur India",
    "price": 310.0,
    "discount_price": 270.0,
    "image_url": "https://placehold.co/200x200/16a34a/ffffff?text=Chyawanprash",
    "dosage_form": "Paste",
    "pack_size": "500g",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Himalaya Liv.52",
    "description": "Herbal liver tonic for liver protection and detox support.",
    "category": "ayurvedic",
    "manufacturer": "Himalaya Wellness",
    "price": 120.0,
    "discount_price": 100.0,
    "image_url": "https://placehold.co/200x200/16a34a/ffffff?text=Liv.52",
    "dosage_form": "Tablet",
    "pack_size": "100 tablets",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Zandu Balm",
    "description": "Ayurvedic pain balm for headache, body ache, and cold relief.",
    "category": "ayurvedic",
    "manufacturer": "Emami Ltd",
    "price": 50.0,
    "discount_price": 42.0,
    "image_url": "https://placehold.co/200x200/16a34a/ffffff?text=Zandu+Balm",
    "dosage_form": "Balm",
    "pack_size": "25ml",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Patanjali Giloy Ghanvati",
    "description": "Giloy extract tablets for immunity, fever, and detoxification.",
    "category": "ayurvedic",
    "manufacturer": "Patanjali Ayurved",
    "price": 80.0,
    "discount_price": 68.0,
    "image_url": "https://placehold.co/200x200/16a34a/ffffff?text=Giloy",
    "dosage_form": "Tablet",
    "pack_size": "60 tablets",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Himalaya Ashvagandha",
    "description": "Ashwagandha extract for stress relief, energy, and vitality.",
    "category": "ayurvedic",
    "manufacturer": "Himalaya Wellness",
    "price": 190.0,
    "discount_price": 165.0,
    "image_url": "https://placehold.co/200x200/16a34a/ffffff?text=Ashvagandha",
    "dosage_form": "Tablet",
    "pack_size": "60 tablets",
    "requires_prescription": False,
    "in_stock": True,
  },

  # ── Personal Care ──────────────────────────────────────
  {
    "name": "Betadine Antiseptic Solution",
    "description": "Povidone-iodine antiseptic for wound cleaning and infection prevention.",
    "category": "personal_care",
    "manufacturer": "Win Medicare",
    "price": 85.0,
    "discount_price": 72.0,
    "image_url": "https://placehold.co/200x200/ec4899/ffffff?text=Betadine",
    "dosage_form": "Solution",
    "pack_size": "100ml",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Dettol Antiseptic Liquid",
    "description": "Multi-purpose antiseptic liquid for skin and surface disinfection.",
    "category": "personal_care",
    "manufacturer": "Reckitt",
    "price": 115.0,
    "discount_price": 99.0,
    "image_url": "https://placehold.co/200x200/ec4899/ffffff?text=Dettol",
    "dosage_form": "Liquid",
    "pack_size": "250ml",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Boroline Cream",
    "description": "Antiseptic ayurvedic cream for dry skin, cuts, and cracked heels.",
    "category": "personal_care",
    "manufacturer": "GD Pharmaceuticals",
    "price": 45.0,
    "discount_price": 38.0,
    "image_url": "https://placehold.co/200x200/ec4899/ffffff?text=Boroline",
    "dosage_form": "Cream",
    "pack_size": "40g",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Moov Pain Relief Spray",
    "description": "Fast-acting spray for muscle pain, sprains, and joint stiffness.",
    "category": "personal_care",
    "manufacturer": "Reckitt",
    "price": 120.0,
    "discount_price": 105.0,
    "image_url": "https://placehold.co/200x200/ec4899/ffffff?text=Moov",
    "dosage_form": "Spray",
    "pack_size": "80g",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Volini Spray",
    "description": "Diclofenac-based pain relief spray for back pain and muscle cramps.",
    "category": "personal_care",
    "manufacturer": "Sun Pharma",
    "price": 190.0,
    "discount_price": 165.0,
    "image_url": "https://placehold.co/200x200/ec4899/ffffff?text=Volini",
    "dosage_form": "Spray",
    "pack_size": "60g",
    "requires_prescription": False,
    "in_stock": True,
  },

  # ── Vitamins & Supplements ─────────────────────────────
  {
    "name": "Supradyn Daily Multivitamin",
    "description": "Complete multivitamin with minerals for daily energy and immunity.",
    "category": "vitamins_supplements",
    "manufacturer": "Abbott India",
    "price": 160.0,
    "discount_price": 138.0,
    "image_url": "https://placehold.co/200x200/8b5cf6/ffffff?text=Supradyn",
    "dosage_form": "Tablet",
    "pack_size": "15 tablets",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Becosules Capsule",
    "description": "B-complex with Vitamin C for mouth ulcers, fatigue, and weakness.",
    "category": "vitamins_supplements",
    "manufacturer": "Pfizer",
    "price": 32.0,
    "discount_price": 27.0,
    "image_url": "https://placehold.co/200x200/8b5cf6/ffffff?text=Becosules",
    "dosage_form": "Capsule",
    "pack_size": "20 capsules",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Shelcal 500",
    "description": "Calcium + Vitamin D3 supplement for bone strength and joint health.",
    "category": "vitamins_supplements",
    "manufacturer": "Elder Pharma",
    "price": 130.0,
    "discount_price": 112.0,
    "image_url": "https://placehold.co/200x200/8b5cf6/ffffff?text=Shelcal",
    "dosage_form": "Tablet",
    "pack_size": "15 tablets",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Limcee Vitamin C 500mg",
    "description": "Chewable Vitamin C tablets for immunity and antioxidant support.",
    "category": "vitamins_supplements",
    "manufacturer": "Abbott India",
    "price": 22.0,
    "discount_price": 18.0,
    "image_url": "https://placehold.co/200x200/8b5cf6/ffffff?text=Limcee",
    "dosage_form": "Chewable Tablet",
    "pack_size": "15 tablets",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Revital H",
    "description": "Daily health supplement with ginseng, vitamins, and minerals.",
    "category": "vitamins_supplements",
    "manufacturer": "Sun Pharma",
    "price": 240.0,
    "discount_price": 210.0,
    "image_url": "https://placehold.co/200x200/8b5cf6/ffffff?text=Revital+H",
    "dosage_form": "Capsule",
    "pack_size": "30 capsules",
    "requires_prescription": False,
    "in_stock": True,
  },

  # ── Baby Care ──────────────────────────────────────────
  {
    "name": "Calpol 250mg Syrup",
    "description": "Paracetamol syrup for children's fever and pain relief.",
    "category": "baby_care",
    "manufacturer": "GSK Pharma",
    "price": 55.0,
    "discount_price": 48.0,
    "image_url": "https://placehold.co/200x200/06b6d4/ffffff?text=Calpol",
    "dosage_form": "Syrup",
    "pack_size": "60ml",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Gripe Water (Woodward's)",
    "description": "Herbal formulation for baby's colic, gas, and stomach discomfort.",
    "category": "baby_care",
    "manufacturer": "TTK Healthcare",
    "price": 65.0,
    "discount_price": 55.0,
    "image_url": "https://placehold.co/200x200/06b6d4/ffffff?text=Gripe+Water",
    "dosage_form": "Liquid",
    "pack_size": "130ml",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Himalaya Baby Cream",
    "description": "Gentle moisturizing cream for baby's delicate skin.",
    "category": "baby_care",
    "manufacturer": "Himalaya Wellness",
    "price": 85.0,
    "discount_price": 72.0,
    "image_url": "https://placehold.co/200x200/06b6d4/ffffff?text=Baby+Cream",
    "dosage_form": "Cream",
    "pack_size": "100ml",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Nasivion Baby Nasal Drops",
    "description": "Saline nasal drops for baby's blocked nose and congestion relief.",
    "category": "baby_care",
    "manufacturer": "Merck",
    "price": 80.0,
    "discount_price": 68.0,
    "image_url": "https://placehold.co/200x200/06b6d4/ffffff?text=Nasivion",
    "dosage_form": "Nasal Drops",
    "pack_size": "10ml",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Dabur Janma Ghunti",
    "description": "Ayurvedic digestive tonic for infants to improve appetite and digestion.",
    "category": "baby_care",
    "manufacturer": "Dabur India",
    "price": 58.0,
    "discount_price": 48.0,
    "image_url": "https://placehold.co/200x200/06b6d4/ffffff?text=Janma+Ghunti",
    "dosage_form": "Syrup",
    "pack_size": "125ml",
    "requires_prescription": False,
    "in_stock": True,
  },

  # ── First Aid ──────────────────────────────────────────
  {
    "name": "Band-Aid Flexible Fabric",
    "description": "Adhesive bandages for minor cuts, scrapes, and wound protection.",
    "category": "first_aid",
    "manufacturer": "Johnson & Johnson",
    "price": 40.0,
    "discount_price": 34.0,
    "image_url": "https://placehold.co/200x200/f97316/ffffff?text=Band-Aid",
    "dosage_form": "Bandage",
    "pack_size": "100 strips",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Soframycin Skin Cream",
    "description": "Framycetin antibiotic cream for cuts, burns, and skin infections.",
    "category": "first_aid",
    "manufacturer": "Sanofi India",
    "price": 68.0,
    "discount_price": 58.0,
    "image_url": "https://placehold.co/200x200/f97316/ffffff?text=Soframycin",
    "dosage_form": "Cream",
    "pack_size": "30g",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Burnol Cream",
    "description": "Antiseptic burn cream for minor burns, scalds, and skin irritation.",
    "category": "first_aid",
    "manufacturer": "Dr. Morepen",
    "price": 55.0,
    "discount_price": 45.0,
    "image_url": "https://placehold.co/200x200/f97316/ffffff?text=Burnol",
    "dosage_form": "Cream",
    "pack_size": "20g",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Savlon Antiseptic Cream",
    "description": "Antiseptic + anti-inflammatory cream for cuts, grazes, and bites.",
    "category": "first_aid",
    "manufacturer": "ITC Ltd",
    "price": 48.0,
    "discount_price": 40.0,
    "image_url": "https://placehold.co/200x200/f97316/ffffff?text=Savlon",
    "dosage_form": "Cream",
    "pack_size": "50g",
    "requires_prescription": False,
    "in_stock": True,
  },
  {
    "name": "Cotton Roll (Sterile)",
    "description": "Medical-grade sterile cotton roll for wound dressing and cleaning.",
    "category": "first_aid",
    "manufacturer": "Surgimed",
    "price": 35.0,
    "discount_price": 28.0,
    "image_url": "https://placehold.co/200x200/f97316/ffffff?text=Cotton+Roll",
    "dosage_form": "Cotton",
    "pack_size": "100g",
    "requires_prescription": False,
    "in_stock": True,
  },

  # ── Chronic Care ───────────────────────────────────────
  {
    "name": "Glycomet GP 2",
    "description": "Metformin + Glimepiride for type 2 diabetes blood sugar control.",
    "category": "chronic_care",
    "manufacturer": "USV Pvt Ltd",
    "price": 135.0,
    "discount_price": 115.0,
    "image_url": "https://placehold.co/200x200/ef4444/ffffff?text=Glycomet+GP",
    "dosage_form": "Tablet",
    "pack_size": "15 tablets",
    "requires_prescription": True,
    "in_stock": True,
  },
  {
    "name": "Amlodipine 5mg",
    "description": "Calcium channel blocker for high blood pressure management.",
    "category": "chronic_care",
    "manufacturer": "Cipla Ltd",
    "price": 30.0,
    "discount_price": 24.0,
    "image_url": "https://placehold.co/200x200/ef4444/ffffff?text=Amlodipine",
    "dosage_form": "Tablet",
    "pack_size": "15 tablets",
    "requires_prescription": True,
    "in_stock": True,
  },
  {
    "name": "Thyronorm 50mcg",
    "description": "Levothyroxine for hypothyroidism — thyroid hormone replacement.",
    "category": "chronic_care",
    "manufacturer": "Abbott India",
    "price": 115.0,
    "discount_price": 98.0,
    "image_url": "https://placehold.co/200x200/ef4444/ffffff?text=Thyronorm",
    "dosage_form": "Tablet",
    "pack_size": "120 tablets",
    "requires_prescription": True,
    "in_stock": True,
  },
  {
    "name": "Atorvastatin 10mg",
    "description": "Statin for high cholesterol and cardiovascular risk reduction.",
    "category": "chronic_care",
    "manufacturer": "Sun Pharma",
    "price": 85.0,
    "discount_price": 72.0,
    "image_url": "https://placehold.co/200x200/ef4444/ffffff?text=Atorvastatin",
    "dosage_form": "Tablet",
    "pack_size": "15 tablets",
    "requires_prescription": True,
    "in_stock": True,
  },
  {
    "name": "Telmisartan 40mg",
    "description": "ARB for hypertension and kidney protection in diabetic patients.",
    "category": "chronic_care",
    "manufacturer": "Glenmark",
    "price": 95.0,
    "discount_price": 80.0,
    "image_url": "https://placehold.co/200x200/ef4444/ffffff?text=Telmisartan",
    "dosage_form": "Tablet",
    "pack_size": "15 tablets",
    "requires_prescription": True,
    "in_stock": True,
  },
]

def seed_medicines():
  """Insert all seed medicines into the in-memory database."""
  seeded = 0

  for med in MEDICINES:
    create_medicine(**med)
    seeded += 1

  print(f"Seeded {seeded} medicines across {len(CATEGORIES)} categories.")
